### ISSUE TITLE
Error when deploying contract to development network

### ISSUE THREAD

**Issue by Asilkin1** [Asilkin1/Blockchain_3800_Final_Project#2]
Starting migrations...
======================
> Network name:    'development'
> Network id:      1605319513876
> Block gas limit: 6721975 (0x6691b7)

1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0xbfabd9f75cf02b550d523fc4b9e3cca4d7c20b0bfc1794f01f5114d5eb264517
   > Blocks: 0            Seconds: 0
   > contract address:    0xaF053Ec63b86EBE2f5977064125dFf443F74423C
   > block number:        8
   > block timestamp:     1605320339
   > account:             0xB7060EdA50dF990C964fcC9A31078f8Cf624e277
   > balance:             99.574526
   > gas used:            221555 (0x36173)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0044311 ETH

   ⠋ Saving migration to chain.
Error: Returned error: VM Exception while processing transaction: invalid opcode
    at Migration._deploy (C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:97:1)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Migration._load (C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:55:1)
    at Migration.run (C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:171:1)
    at Object.runMigrations (C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.run (C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:87:1)
    at runMigrations (C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:269:1)
    at C:\Users\silkina\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:231:1
Truffle v5.1.49 (core: 5.1.49)
Node v12.14.1

**Comment by Asilkin1** [comment]
Probably related to the attempt of migrating the same contract twice.
